# Generated by Django 5.0 on 2024-02-10 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('base_price', models.PositiveIntegerField()),
                ('hero_image', models.ImageField(default='listings/placeholder-image.png', max_length=250, upload_to='listings/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buying_format', models.CharField(choices=[('BIN', 'Buy It Now'), ('A', 'Auction'), ('AO', 'Accept Offers')], default='A', max_length=3)),
                ('free_shipping', models.BooleanField(default=False)),
                ('local_pickup', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('purchased', models.BooleanField(default=False)),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auctions.listing')),
                ('end_date', models.DateTimeField()),
                ('highest_bid_amount', models.PositiveIntegerField()),
                ('auction_status', models.CharField(choices=[('S', 'Sold'), ('O', 'Ongoing')], default='O', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='BuyItNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_buyer', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.paymentmethod')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.condition'),
        ),
        migrations.CreateModel(
            name='ListingAdditionalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=250, upload_to='listings/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.listing')),
            ],
            options={
                'verbose_name_plural': 'Listing Additional Images',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.location'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('offer_status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('C', 'Counter'), ('P', 'Pending')], default='P', max_length=2)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_buyer', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.paymentmethod')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounterOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_offer', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('counter_offer_status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('P', 'Pending')], default='P', max_length=2)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bid_status', models.CharField(choices=[('W', 'Won'), ('L', 'Lost'), ('O', 'Ongoing')], default='O', max_length=2)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_buyer', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.paymentmethod')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.address')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
