# Generated by Django 5.0 on 2024-02-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counteroffer',
            old_name='counter_offer',
            new_name='counter_offer_amount',
        ),
    ]
