# Generated by Django 5.0 on 2024-02-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_counter_offer_counteroffer_counter_offer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_status',
            field=models.CharField(choices=[('S', 'Sold'), ('O', 'Ongoing'), ('CWS', 'Closed Without Sale')], default='O', max_length=3),
        ),
        migrations.AlterField(
            model_name='counteroffer',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='auctions.offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('C', 'Counter'), ('CA', 'Counter Accepted'), ('CR', 'Counter Rejected'), ('P', 'Pending')], default='P', max_length=2),
        ),
    ]
