# Generated by Django 5.0 on 2024-02-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_options_alter_buyitnow_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='buyer',
        ),
    ]
