# Generated by Django 5.0 on 2024-02-01 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_bid_shipping_address'),
        ('users', '0010_user_previous_email_alter_bkashpayment_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startBid',
            new_name='starting_price',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid', to='users.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid', to='users.address'),
        ),
    ]
