# Generated by Django 5.0 on 2024-02-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_rename_startbid_listing_starting_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listedBy',
            new_name='listed_by',
        ),
    ]
