# Generated by Django 5.0 on 2024-02-02 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_buyingformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='buying_format',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='auctions.buyingformat'),
        ),
    ]
