# Generated by Django 5.0 on 2024-02-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_buying_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingformat',
            name='default_instance',
            field=models.BooleanField(default=False),
        ),
    ]
