# Generated by Django 5.0 on 2024-02-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_buyingformat_default_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyingformat',
            name='default_instance',
        ),
        migrations.AlterField(
            model_name='listing',
            name='buying_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.buyingformat'),
        ),
    ]
