# Generated by Django 5.0 on 2024-02-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_category_condition_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingformat',
            name='action_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
