# Generated by Django 5.0 on 2024-02-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.condition'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.location'),
        ),
    ]
