# Generated by Django 5.0 on 2024-02-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_acceptsofferslisting_auctionlisting_bidstatus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BidStatus',
            new_name='CounterOfferStatus',
        ),
        migrations.DeleteModel(
            name='AcceptsOffersListing',
        ),
    ]
