# Generated by Django 5.0 on 2024-02-06 16:29

import auctions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_bidstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_status',
            field=models.ForeignKey(default=auctions.models.BidStatus.get_default_bid_status, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.bidstatus'),
        ),
    ]
