# Generated by Django 5.0 on 2024-02-06 17:01

import auctions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_bid_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='counteroffer',
            name='status',
            field=models.ForeignKey(default=auctions.models.CounterOfferStatus.get_default_counter_offer_status, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.counterofferstatus'),
        ),
    ]
